name: takenotes
grade: stable
license: GPL-3.0+
summary: it is a test app
description: |
  it is a simple app to take notes
version: '1'
base: core18
confinement: strict

apps:
  takenotes:
    command: bin/takenotes.py
    extensions: [gnome-3-28]
    plugs:
      - home
    slots:
      - dbus-daemon
    common-id: br.com.labs.Takenotes

parts:
  takenotes:
    plugin: python
    source: .
    build-packages:
      - python3


  dump-files:
    plugin: dump
    source: .
    organize:
      takenotes.py: bin/

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: br.com.labs.Takenotes


layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0
  /usr/share/xml/iso-codes:
    bind: $SNAP/gnome-platform/usr/share/xml/iso-codes